version: 0.0
os: linux
files:
  - source: /
    destination: /Brain-Tasks-App

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/deploy_k8s.sh
      timeout: 300
      runas: root

