apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: brain-tasks-pipeline
description: GKE delivery pipeline
serialPipeline:
  stages:
    - targetId: gke-target
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gke-target
gke:
  cluster: projects/astute-ace-286718/locations/us-central1/clusters/gke-cluster
  internalIp: false

