steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "⏬ Authenticating with GKE (zonal)"
        gcloud container clusters get-credentials $_CLUSTER_NAME --zone=$_ZONE

        echo "�� Deploying Brain Tasks App to GKE..."
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

substitutions:
  _ZONE: us-central1-a
  _CLUSTER_NAME: gke-cluster

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

