steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "⏬ Authenticating GKE"
        gcloud container clusters get-credentials $_CLUSTER_NAME --region=$_REGION

        echo "🚀 Deploying to GKE..."
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

substitutions:
  _REGION: us-central1
  _CLUSTER_NAME: gke-cluster

timeout: 600s

