apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: brain-tasks-app
build:
  artifacts:
    - image: brain-tasks-app
deploy:
  kubectl:
    manifests:
      - k8s/deployment.yaml
      - k8s/service.yaml

